// This source code is subject to the terms of the Osozilla Public License 2.0 at https://mozilla.org/OsPL/2.0/
// © BlueJayBird
// @author @BlueJayBird
// @version=4

study(title = "[bjb] OS - Oscillator Signals, by @BlueJayBird", shorttitle = "OS", precision = 2, format = format.price, overlay = true)

// If this tool has helped you to improve your trading and therefore your income, any donation is appreciated:
// BTC: 3Dj9jfGuJ861oEH7kA1zpgMssPw2PYF7Gq
// ETH and USDT: 0xc8645305ab8c08f08bcbc89c020b63362527f771

// OSCILLATOR SIGNALS -----------------------------------------------------------------
// ----------------- INPUTS
// Constants
transparencyOsSignals = 20
drawOnRealTime = true // "Draw On Candles Yet To Close"
// User inputs
type = input(title = "Oscillator Signals Type", defval = "RSI", options = ["MFI", "RSI"])
enableOsSignals = input(title = "Enable OS", type = input.bool, defval = true)
length = input(14, minval = 1, title = "Length")

// ----------------- CALCULATIONS
source = type == "MFI" ? hlc3 : type == "RSI" ? close : na
mode = type == "MFI" ? mfi(source, length) : type == "RSI" ? rsi(source, length) : na
overbought = type == "MFI" ? 80 : type == "RSI" ? 70 : na
oversold = type == "MFI" ? 20 : type == "RSI" ? 30 : na

// ----------------- PLOTTING
// OsI Signal Levels: Def Values, 1, 5, 15, 60, 240
// Green
signalOs1 = input(title = "OS1 Resolution", defval = "1", type = input.resolution)
securityOs1 = security(syminfo.tickerid, signalOs1, mode)
obOs1 = securityOs1 >= overbought
osOs1 = securityOs1 <= oversold
plotshape(obOs1 and enableOsSignals and (barstate.ishistory or drawOnRealTime), color = color.green, transp = transparencyOsSignals, text = "", style = shape.triangledown, title = "OB OS1", location = location.abovebar)
plotshape(osOs1 and enableOsSignals and (barstate.ishistory or drawOnRealTime), color = color.green, transp = transparencyOsSignals, text = "", style = shape.triangleup, title = "OS OS1", location = location.belowbar)
// Yellow
signalOs2 = input(title = "OS2 Resolution", defval = "5", type = input.resolution)
securityOs2 = security(syminfo.tickerid, signalOs2, mode)
obOs2 = securityOs2 >= overbought
osOs2 = securityOs2 <= oversold
plotshape(obOs2 and enableOsSignals and (barstate.ishistory or drawOnRealTime), color = color.yellow, transp = transparencyOsSignals, text = "", style = shape.triangledown, title = "OB OS2", location = location.abovebar)
plotshape(osOs2 and enableOsSignals and (barstate.ishistory or drawOnRealTime), color = color.yellow, transp = transparencyOsSignals, text = "", style = shape.triangleup, title = "OS OS2", location = location.belowbar)
// Red
signalOs3 = input(title = "OS3 Resolution", defval = "15", type = input.resolution)
securityOs3 = security(syminfo.tickerid, signalOs3, mode)
obOs3 = securityOs3 >= overbought
osOs3 = securityOs3 <= oversold
plotshape(obOs3 and enableOsSignals and (barstate.ishistory or drawOnRealTime), color = color.red, transp = transparencyOsSignals, text = "", style = shape.triangledown, title = "OB OS3", location = location.abovebar)
plotshape(osOs3 and enableOsSignals and (barstate.ishistory or drawOnRealTime), color = color.red, transp = transparencyOsSignals, text = "", style = shape.triangleup, title = "OS OS3", location = location.belowbar)
// White
signalOs4 = input(title = "OS4 Resolution", defval = "60", type = input.resolution)
securityOs4 = security(syminfo.tickerid, signalOs4, mode)
obOs4 = securityOs4 >= overbought
osOs4 = securityOs4 <= oversold
plotshape(obOs4 and enableOsSignals and (barstate.ishistory or drawOnRealTime), color = color.white, transp = transparencyOsSignals, text = "", style = shape.triangledown, title = "OB OS4", location = location.abovebar)
plotshape(osOs4 and enableOsSignals and (barstate.ishistory or drawOnRealTime), color = color.white, transp = transparencyOsSignals, text = "", style = shape.triangleup, title = "OS OS4", location = location.belowbar)
// Purple
signalOs5 = input(title = "OS5 Resolution", defval = "240", type = input.resolution)
securityOs5 = security(syminfo.tickerid, signalOs5, mode)
obOs5 = securityOs5 >= overbought
osOs5 = securityOs5 <= oversold
plotshape(obOs5 and enableOsSignals and (barstate.ishistory or drawOnRealTime), color = color.purple, transp = transparencyOsSignals, text = "", style = shape.triangledown, title = "OB OS5", location = location.abovebar)
plotshape(osOs5 and enableOsSignals and (barstate.ishistory or drawOnRealTime), color = color.purple, transp = transparencyOsSignals, text = "", style = shape.triangleup, title = "OS OS5", location = location.belowbar)
// END -------------------------------------------------------------------------