// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © BlueJayBird

// TODO: Make the script automatic. For example, do not display session VWAP at timeframes equal or higer than 1D.

//@version=4
study(title="VCB - Visual Candlestick Blender", shorttitle="VCB", overlay=true)

// Style
thickness = 2
transp_ma = 40
transp_fill = 90
transp_fill_20 = 80
securityGap = barmerge.gaps_off 
securityLookahead = barmerge.lookahead_on

// ------------------------------------- Enable VCB
enable1 = input(defval = true,  title = "Enable Visual Candlestick Blendings 1 (VCB1)")
enable2 = input(defval = false, title = "Enable Visual Candlestick Blendings 2 (VCB2)")
enable3 = input(defval = false, title = "Enable Visual Candlestick Blendings 3 (VCB3)")
enable4 = input(defval = false, title = "Enable Visual Candlestick Blendings 4 (VCB4)")

// ------------------------------------- Resolutions VCB
res1 = input(title = "VCB1 Resolution", defval = "60", type = input.resolution)
res2 = input(title = "VCB2 Resolution", defval = "240", type = input.resolution)
res3 = input(title = "VCB3 Resolution", defval = "D", type = input.resolution)
res4 = input(title = "VCB4 Resolution", defval = "W", type = input.resolution)

// ------------------------------------- VCB Plotting 1
o1 = security(syminfo.ticker, res1, open, securityGap, securityLookahead)
h1 = security(syminfo.ticker, res1, high, securityGap, securityLookahead)
l1 = security(syminfo.ticker, res1, low, securityGap, securityLookahead)
c1 = security(syminfo.ticker, res1, close, securityGap, securityLookahead)
palette1 = c1 > o1 ? color.lime : color.red
paletteTraslucid1 = c1 > o1 ? color.new(color.lime, 50) : color.new(color.red, 50)
dashedWorkaround1 = bar_index % 2 == 0 ? palette1 : paletteTraslucid1
plot(enable1 ? o1 : na, title="O1", color=palette1, linewidth=thickness + 1, transp=transp_ma, editable=true, style=plot.style_stepline)
plot(enable1 ? h1 : na, title="H1", color=dashedWorkaround1, linewidth=thickness, transp=70, editable=true, style=plot.style_stepline)
plot(enable1 ? l1 : na, title="L1", color=dashedWorkaround1, linewidth=thickness, transp=70, editable=true, style=plot.style_stepline)
plot(enable1 ? c1 : na, title="C1", color=palette1, linewidth=thickness + 1, transp=transp_ma, editable=true, style=plot.style_stepline)

// ------------------------------------- VCB Plotting 2
o2 = security(syminfo.ticker, res2, open, securityGap, securityLookahead)
h2 = security(syminfo.ticker, res2, high, securityGap, securityLookahead)
l2 = security(syminfo.ticker, res2, low, securityGap, securityLookahead)
c2 = security(syminfo.ticker, res2, close, securityGap, securityLookahead)
palette2 = c2 > o2 ? color.aqua : color.yellow
paletteTraslucid2 = c2 > o2 ? color.new(color.aqua, 50) : color.new(color.yellow, 50)
dashedWorkaround2 = bar_index % 2 == 0 ? palette2 : paletteTraslucid2
plot(enable2 ? o2 : na, title="O2", color=palette2, linewidth=thickness + 1, transp=transp_ma, editable=true, style=plot.style_stepline)
plot(enable2 ? h2 : na, title="H2", color=dashedWorkaround2, linewidth=thickness, transp=70, editable=true, style=plot.style_stepline)
plot(enable2 ? l2 : na, title="L2", color=dashedWorkaround2, linewidth=thickness, transp=70, editable=true, style=plot.style_stepline)
plot(enable2 ? c2 : na, title="C2", color=palette2, linewidth=thickness + 1, transp=transp_ma, editable=true, style=plot.style_stepline)

// ------------------------------------- VCB Plotting 3
o3 = security(syminfo.ticker, res3, open, securityGap, securityLookahead)
h3 = security(syminfo.ticker, res3, high, securityGap, securityLookahead)
l3 = security(syminfo.ticker, res3, low, securityGap, securityLookahead)
c3 = security(syminfo.ticker, res3, close, securityGap, securityLookahead)
palette3 = c3 > o3 ? color.orange : color.fuchsia
paletteTraslucid3 = c3 > o3 ? color.new(color.orange, 50) : color.new(color.fuchsia, 50)
dashedWorkaround3 = bar_index % 2 == 0 ? palette3 : paletteTraslucid3
plot(enable3 ? o3 : na, title="O3", color=palette3, linewidth=thickness + 1, transp=transp_ma, editable=true, style=plot.style_stepline)
plot(enable3 ? h3 : na, title="H3", color=dashedWorkaround3, linewidth=thickness, transp=70, editable=true, style=plot.style_stepline)
plot(enable3 ? l3 : na, title="L3", color=dashedWorkaround3, linewidth=thickness, transp=70, editable=true, style=plot.style_stepline)
plot(enable3 ? c3 : na, title="C3", color=palette3, linewidth=thickness + 1, transp=transp_ma, editable=true, style=plot.style_stepline)

// ------------------------------------- VCB Plotting 4
o4 = security(syminfo.ticker, res4, open, securityGap, securityLookahead)
h4 = security(syminfo.ticker, res4, high, securityGap, securityLookahead)
l4 = security(syminfo.ticker, res4, low, securityGap, securityLookahead)
c4 = security(syminfo.ticker, res4, close, securityGap, securityLookahead)
palette4 = c4 > o4 ? color.yellow : color.orange
paletteTraslucid4 = c4 > o4 ? color.new(color.yellow, 50) : color.new(color.orange, 50)
dashedWorkaround4 = bar_index % 2 == 0 ? palette4 : paletteTraslucid4
plot(enable4 ? o4 : na, title="O4", color = palette4, linewidth = thickness + 1, transp = transp_ma, editable = true, style = plot.style_stepline)
plot(enable4 ? h4 : na, title="H4", color = dashedWorkaround4, linewidth = thickness, transp = 70, editable = true, style = plot.style_stepline)
plot(enable4 ? l4 : na, title="L4", color = dashedWorkaround4, linewidth = thickness, transp = 70, editable = true, style = plot.style_stepline)
plot(enable4 ? c4 : na, title="C4", color = palette4, linewidth = thickness + 1, transp = transp_ma, editable = true, style = plot.style_stepline)